### ISSUE TITLE
The CodeTour (step #9 of 10) references videos when there are none

### ISSUE THREAD

**Issue by mraible** [auth0-training/labs-node-working-with-tenants#3]
### Description

The CodeTour (step #9 of 10) says to click on Videos in the top navigation. 

<img width="775" alt="Screenshot 2023-04-03 at 10 30 53 AM" src="https://user-images.githubusercontent.com/17892/229571790-841f5c96-0851-455f-80ae-72a2a9a0831d.png">

There are no videos in the top navigation of https://auth0.com/docs. 

<img width="1081" alt="Screenshot 2023-04-03 at 10 32 57 AM" src="https://user-images.githubusercontent.com/17892/229571902-87d69869-de53-4a81-94c5-f5ee798e4bae.png">

**Comment by kateharney** [comment]
Thanks! Removed reference to videos.
