### ISSUE TITLE
Slide references Angular.JS, which hasn't been a thing since 2016

### ISSUE THREAD

**Issue by mraible** [auth0-training/labs-node-working-with-tenants#4]
### Description

A slide in the Auth0 Fundamentals course references "Angular.JS" when talking about Single Page Applications. AngularJS is a synonym for Angular 1.x and hasn't been a thing since Angular 2 was released in September 2016. Since then, they've dropped the version number when referring to the framework, and now it's just called Angular. 

### Reproduction

I believe this slide should be updated so our training doesn't look like it's from 2016. 

<img width="344" alt="Screenshot 2023-04-03 at 10 41 10 AM" src="https://user-images.githubusercontent.com/17892/229574344-d85a2519-f304-4fee-8de2-155c34b6ce6a.png">

**Comment by mraible** [comment]
@kazemicode Let me know if you need any help!

**Comment by kazemicode** [comment]
Closing since new version of the course is in development and slated for June!
